# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-06 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentstemmap',
            name='rank_component',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stem',
            name='idf',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
